### ISSUE TITLE
As a user, I want to be able filter artists by more options.

### ISSUE THREAD

**Issue by RobertHale** [connormlewis/idb#168]
I'm only going to note this here, but maybe consider splitting the sort options and the ascending/descending option. Personally, I think it feels better that way.

**Comment by aylish19** [comment]
@RobertHale 
We can do the splitting of the sort and ascending/descending options. 
We've already added all meaningful artist sorting options. The only ones we could easily add right now are trivial ones like id or spotify uri. 

Is there any particular sorting option you're looking for?

**Comment by aylish19** [comment]
New filtering option: existence of biography information

**Comment by aylish19** [comment]
Added number of related model instances
Estimated time: 3 hours
Actual time: 2 hours
