### ISSUE TITLE
As a user, I want to be able sort artists by more options.

### ISSUE THREAD

**Issue by RobertHale** [connormlewis/idb#169]

**Comment by aylish19** [comment]
@RobertHale
We can do the splitting of the sort and ascending/descending options.
We've already added all meaningful artist sorting options. The only ones we could easily add right now are trivial ones like id or spotify uri.

Is there any particular sorting option you're looking for?

**Comment by RobertHale** [comment]
When my team looked at it, the options just looked too limited. Maybe look into sorting by its connection to other models. One possibility is sorting by number of albums made by the artist.

**Comment by aylish19** [comment]
Options: Number of related model instances
