### ISSUE TITLE
As a developer, I would like to have more fine grained filter control over the data that I can query.

### ISSUE THREAD

**Issue by RobertHale** [connormlewis/idb#174]
the filter for the API currently feels lacking and custom designed for the site rather than for users. Consider adding general purpose filters that filter by any specified attribute.

**Comment by aylish19** [comment]
Relates to #161 and #159

**Comment by aylish19** [comment]
Relates to #167 and #168

**Comment by aylish19** [comment]
Actual time: 1 hour
