### ISSUE TITLE
As a user, I would like the site to be mobile friendly. (it does very weird stuff on mobile)

### ISSUE THREAD

**Issue by RobertHale** [connormlewis/idb#175]
We know mobile compatibility is not a huge issue, but certain parts of the website are not looking good to the mobile user.

**Comment by aylish19** [comment]
Home Page: scrolls left and right, photos too large 
Instance pages: sliders don't shrink, causes screen to scroll left and right 
About: tools #165

**Comment by aylish19** [comment]
Estimated time: 5 hours

**Comment by tsukkisuki** [comment]
Actual: 9 hours 35 minutes
