### ISSUE TITLE
Collect 3 examples for each model

### ISSUE THREAD

**Issue by connormlewis** [connormlewis/idb#2]
- [ ] Album
- [ ] Artist
- [ ] Movie/TV

**Comment by tsukkisuki** [comment]
Examples to use:

- Album
> Interstellar: Original Motion Picture Soundtrack
> Riverdale: Original Television Score (Season 1)
> E.T. The Extra-Terrestrial (Music From The Original Motion Picture Soundtrack)

- Artist
> Hans Zimmer
> Blake Neely
> John Wiliams

- Movie/TV
> Interstellar
> Riverdale
> E.T.

**Comment by tsukkisuki** [comment]
Collected examples, pushed to repository under idb/static/instances/
