### ISSUE TITLE
Get API Keys

### ISSUE THREAD

**Issue by aylish19** [connormlewis/idb#4]
The API's we plan to use will most likely require keys to access them. We should request these keys as soon as possible and store them somewhere safe. As of today (2/10), the API's we plan to use are: 
https://developer.spotify.com/web-api/
https://www.last.fm/api
https://www.themoviedb.org/documentation/api
https://api.thetvdb.com/swagger
https://www.traileraddict.com/trailerapi

**Comment by melxtru** [comment]
API keys are in a GoogleDoc posted in Slack
