### ISSUE TITLE
As a customer, I can see if new functionality breaks old code using well-written, thorough unit testing

### ISSUE THREAD

**Issue by connormlewis** [connormlewis/idb#44]
This should be performed throughout the process of writing any new code. This makes estimating this story somewhat difficult.

An initial chunk of time will need to be dedicated to setting up the testing environments and testing frameworks. 
Estimated time: 6 (Mocha = 2, Selenium = 2, Travis = 1, Python unittest = 1)

**Comment by aylish19** [comment]
Python unittests and travis setup are done.
Mocha has been sent up and many frontend tests have been written. We should add some error handling tests as well.
Selenium still needs to be done.
Time spent so far: 15 hours

**Comment by aylish19** [comment]
Actual time: 21 hours
