### ISSUE TITLE
Create simple API that returns existing 3 models

### ISSUE THREAD

**Issue by connormlewis** [connormlewis/idb#46]
- [x] Modify the existing JSON files to look like what our api will eventually return
- [x] Rewrite the flask portion of the product to return these pages when called, rather than returning the templates like it did for project 1

This will allow for accessing of the database to be a drop in replacement once it's done, and allow other team members to simultaneously work on the front end

**Comment by connormlewis** [comment]
@TheSchaft completed this with #78

**Comment by aylish19** [comment]
Estimated Time: 3 hours
Actual Time: 6 hours
